---
title: "tlverse Schematic Data"
output:
  html_document:
  df_print: paged
---
  
# Setup
```{r setup}
knitr::opts_chunk$set(echo=FALSE, results = "hide")
library(ggplot2)
library(sl3)
library(tmle3)
library(MASS)
library(data.table)
library(viridis)
set.seed(1234)
```

## DGP
```{r dgp, echo = TRUE}
# set.seed(1237)
# setwd("~/Dropbox/gates/nature/schematic_sim/")
# define DGD
g <- function(W){
  pA <- plogis(-0.1 * W)
  return(pA)
}

Q <- function(A,W){
  EY = 0.2*(-10 * A + W - 0.2*W^2 + 0.4*A*W^2)
  return(EY)
}

gen_data <- function(n, eps_sd = 0.2){
  W <- sample(1:10,n,replace=TRUE)
  pA <- g(W)
  A <- rbinom(n,1,pA)
  EY <- Q(A,W)
  EY1 <- Q(1,W)
  EY0 <- Q(0,W)
  EYa <- Q(1,W)*g(W)+Q(0,W)*(1-g(W))
  d0 <- as.numeric(EY1>EY0)
  EYd0 <- ifelse(d0,EY1,EY0)
  
  
  Y <- EY + 2*rnorm(n,0,eps_sd)
  data <- data.table(W,pA,A,Y,EY,EY1,EY0,EYa,d0,EYd0)
  
}

data <- gen_data(100)
```

```{r calc_psi_0}
# Calc true parameters via simple MC sim
test_data <- gen_data(1e6)
sapply(data,quantile)
EY1_truth <- mean(test_data$EY1)
ATE_truth <- mean(test_data$EY1-test_data$EY0)
schematic_xlim=c(1,10)
schematic_ylim=c(min(pmin(test_data$EY0,test_data$EY1,test_data$Y)),
                 max(pmax(test_data$EY0,test_data$EY1,test_data$Y)))
```

```{r save_data}
# TODO: Document your data (see 'https://r-pkgs.org/data.html')
schematic_full <- data
schematic <- data[,list(W,A,Y)]
usethis::use_data(schematic, schematic_full, 
                  schematic_xlim, schematic_ylim, overwrite = TRUE)
```



```{r plot_settings}
# global plot settings
point_alpha = 1
global_xlim=c(1,10)
global_ylim=c(min(pmin(test_data$EY0,test_data$EY1,test_data$Y)),max(pmax(test_data$EY0,test_data$EY1,test_data$Y)))
cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
# cbPalette <- cbbPalette[c(2,3,6,7)]
cbPalette <- viridis_pal()(4)[c(1,3,2,4)]

make_plots <- function(plotobj, name, 
                       height=3, width=5, 
                       make_pdf=FALSE, make_png = FALSE){
  print(plotobj)
  
  if(make_pdf){
    pdf(sprintf("figures/%s.pdf",name),height=height,width=width)
    print(plotobj)
    dev.off()
  }
  
  if(make_png){
    png(sprintf("figures/%s.png",name),height=300*height,width=300*width,res=300)
    print(plotobj)
    dev.off()
  }
}

plot_schematic <- function(data, cf_data, cf_mean){
  
  type_guide <- ifelse(length(unique(cf_data$type))>1,"legend",FALSE)
  plotobj <- ggplot(data,aes(x=W,y=Y, color=factor(A)))+
    geom_point(alpha=point_alpha)+
    geom_line(data=cf_data,aes(linetype=type))+theme_bw()+
    xlab("Covariate")+ylab("Outcome")+
    scale_color_manual("Treatment Level",values=cbPalette)+
    scale_linetype_discrete("Estimation", guide = type_guide)+
    xlim(global_xlim)+ylim(global_ylim)+
    geom_rug(data=cf_mean,aes(linetype=type), sides="r")
  return(plotobj)
}
```

# True DGD

```{r plot_true_dgd}
cf_data <- melt(data,id="W",measure=c("EY0","EY1","EYa"),value.name = "Y")
cf_data[,A:=factor(variable,levels=c("EY0","EY1","EYa"),labels=c("0","1","Observed"))]
cf_data <- cf_data[A!="Observed"]
cf_data$type <- "true"
cf_mean <- cf_data[,list(Y=mean(Y),W=0),by=list(A,type)]

make_plots(plot_schematic(data,cf_data,cf_mean), "schematic_1_truedgd")
```

# Estimated DGD

```{r plot_estimated_dgd}
######################
# plot estimated DGD
# data <- gen_data(n)
Q_glm <- glm(Y~A+W,data, family="gaussian")
Q_glm_summary <- summary(Q_glm)
ATE_glm_ci <- confint(Q_glm,"A")
ATE_glm <- coef(Q_glm)[["A"]]


data_A0 <- data
data_A0$A <- 0

data_A1 <- data
data_A1$A <- 1

data$pred_glm_EY1 <- predict(Q_glm, data_A1)
data$pred_glm_EY0 <- predict(Q_glm, data_A0)
glm_cf_pred <- melt(data,id="W",measure=c("pred_glm_EY0","pred_glm_EY1"),value.name = "Y")
glm_cf_pred[,A:=as.numeric(variable=="pred_glm_EY1")]
glm_cf_pred$type <- "glm"
glm_cf_mean <- glm_cf_pred[,list(Y=mean(Y),W=0),by=list(A,type)]

make_plots(plot_schematic(data,glm_cf_pred,glm_cf_mean),"schematic_2a_glmlik")
```
